# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Adrian Marinescu`s Blog'
tagline:          'Adrian Marinescu`s Personal Blog'
description:      'Adrian Marinescu`s Personal Blog'
url:              'https://marinescuadrian.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Search
  url: /search/


# Author Details
author:         'Adrian Marinescu'

#Social Media links (Use complete URL except for email)
facebook:       'https://facebook.com/marinescu.adrian.crypto'
github:         'https://github.com/marinescuadrian'
instagram:      'https://www.instagram.com/adi.marinescu/'
linkedin:       'https://www.linkedin.com/in/adrian-marinescu/'
twitter:        'https://twitter.com/marinescuadi'

# Google Analytics
gahandler: 'UA-XXXXXXXX-X'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'adrianmarinescu'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
